version: "3"
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    volumes:
      - db_sql:/var/lib/mysql
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: BroXlx2012Scr
      MYSQL_DATABASE: administration_users
      MYSQL_USER: scrberexia
      MYSQL_PASSWORD: BroXlx2012Scr
    restart: always
    networks:
      - scr

  administration-service:
    restart: always
    container_name: administration-service
    build: .
    depends_on:
      - mysql-db
    ports:
      - 9090:8080
    networks:
      - scr

volumes:
  db_sql:

networks:
  scr:
    driver: bridge